# version: '3.8'

#   # postgres:
#   #   image: postgres:latest
#   #   container_name: postgres-db
#   #   environment:
#   #     POSTGRES_USER: postgres
#   #     POSTGRES_PASSWORD: root123
#   #     POSTGRES_DB: polling-system
#   #   ports:
#   #     - "5432:5432"
#   #   volumes:
#   #     - postgres-data:/var/lib/postgresql/data

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     container_name: zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     container_name: kafka
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#     ports:
#       - "9092:9092"

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: node-app
#     environment:
#       KAFKA_BROKER: kafka:9092
#       POSTGRES_URI: postgres://postgres:root123@postgres-db:5432/polling-system
#     depends_on:
#       - kafka
#       # - postgres
#     ports:
#       - "3000:3000"

# # volumes:
# #   postgres-data:



version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9092:9092"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      KAFKA_BROKER: kafka:9092
      # Adjusted POSTGRES_URI to point to the host Postgres
      POSTGRES_URI: postgres://postgres:root123@host.docker.internal:5432/polling-system
    depends_on:
      - kafka
    ports:
      - "3000:3000"
